### ISSUE TITLE
DBIish and Text::CSV do not work together.

### ISSUE THREAD

**Issue by wbiker** [Tux/CSV#1]
Hmm, probably not a CSV problem alone. However, I would use CSV and DBIish together in a script, but every time I include both and run it the following error is thrown:

Merging GLOBAL symbols failed: duplicate definition of symbol HLL
This happens in the DBIish.connect method.
I will this also post on the DBIish repo.

$ perl6
> use DBIish
> use Text::CSV
my $dbh = DBIish.connect("SQLite", :database<new-database.sqlite3>)

**Comment by Tux** [comment]
On Sat, 29 Aug 2015 04:23:44 -0700, Wolf <notifications@github.com>
wrote:

> Hmm, probably not a CSV problem alone. However, I would use CSV and DBIish together in a script, but every time I include both and run it the following error is thrown:
> 
> Merging GLOBAL symbols failed: duplicate definition of symbol HLL
> This happens in the DBIish.connect method.
> I will this also post on the DBIish repo.
> 
> $ perl6
> > use DBIish
> > use Text::CSV  
> my $dbh = DBIish.connect("SQLite", :database<new-database.sqlite3>)

I think this was fixed about between 15-Aug and 23-Aug

maybe ed32f95dc1

-- 
H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.21   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by wbiker** [comment]
Hi, thanks!
I upgraded rakudobrew and moar and the error goes away.
Sorry
