### ISSUE TITLE
perl6 --doc CSV.pod6 fails with Rakudo Star 2018.01

### ISSUE THREAD

**Issue by zaucker** [Tux/CSV#10]
perl6 --doc lib/Text/CSV.pod6
===SORRY!=== Error while compiling /home/zaucker/checkouts/CSV/lib/Text/CSV.pod6
Two terms in a row
at /home/zaucker/checkouts/CSV/lib/Text/CSV.pod6:6
------> nslated yet into correct perl6 idiom. My⏏ bad. Sorry.
    expecting any of:
        infix
        infix stopper
        postfix
        statement end
        statement modifier
        statement modifier loop

with

perl6 -v
This is Rakudo Star version 2018.01 built on MoarVM version 2018.01
implementing Perl 6.c.

**Comment by Tux** [comment]
Feedback on IRC revealed that .pod and .pod6 does not imply pod. The document needs begin and end tags, which are added in cf170de103dcdc0fb7e418705926067702a91b48
