### ISSUE TITLE
Failures with 2018.06

### ISSUE THREAD

**Issue by JJ** [Tux/CSV#12]
Due to the change in ordering of hashes, this now fails:

```
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "baz", "bar"], ["3", "2", "1"], ["", "a b", "2"]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "baz", "bar"], ["3", "2", "1"], ["", "a b", "2"]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "baz", "bar"], ["3", "2", "1"], ["", "a b", "2"]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "baz", "bar"], ["3", "2", "1"], ["", "a b", "2"]]
# Failed test 'csv => Str   (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
```

**Comment by lizmat** [comment]
@Tux: I've looked at it, but am unsure on how to proceed, as I'm a bit too unfamiliar with the "in" functionality

**Comment by JJ** [comment]
I checked it out and forked it, and I think that we could solve lots of
problems like this changing the is-deeply test. Or creating a
is-deeply-sorted or something like that.
If not, there's going to be  non-uniform and inconsistent changes ranging
from deleting the tests to major refactoring...

**Comment by Tux** [comment]
Thinking about it ...

**Comment by Tux** [comment]
Working on it, but in that process I found new issues that I cannot push yet. Work in progress, not stalled

**Comment by JJ** [comment]
Will do. Thanks for warning.

**Comment by JJ** [comment]
It's all good now.
