### ISSUE TITLE
Failed zef install  with rakudo-star-2019.03-RC.tar.gz

### ISSUE THREAD

**Issue by michael-776** [Tux/CSV#13]
Hello,

You may already be aware of this problem, but here it is just in case.

perl6 --version
This is Rakudo Star version 2019.03 built on MoarVM version 2019.03
implementing Perl 6.d.

Complete log included, as I was not sure what it was OK to delete:

===> Searching for: Text::CSV
===> Searching for missing dependencies: Slang::Tuxic
===> Testing: Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
===> Testing [OK] for Slang::Tuxic:ver<0.0.1>:auth<github:FROGGS>
===> Testing: Text::CSV:ver<0.008>:auth<github:Tux>
TODO: EOL = "!", RS = ""
      "1,2,3!4,5,6!"
  --> ["1"]
TODO: EOL = "!!", RS = ""
      "1,2,3!!4,5,6!!"
  --> ["1"]
TODO: EOL = "!!", RS = "!"
      "1,2,3!!4,5,6!!"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n", RS = ""
      "1,2,3!\n4,5,6!\n"
  --> ["1"]
TODO: EOL = "!\n", RS = "!"
      "1,2,3!\n4,5,6!\n"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n!", RS = ""
      "1,2,3!\n!4,5,6!\n!"
  --> ["1"]
TODO: EOL = "!\n!", RS = "\n"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!\n"]
TODO: EOL = "!\n!", RS = "!"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!"]
TODO: EOL = "!\n!", RS = "!\n"
      "1,2,3!\n!4,5,6!\n!"
  --> ["1", "2", "3!\n"]
TODO: EOL = "!!!!!!!!", RS = ""
      "1,2,3!!!!!!!!4,5,6!!!!!!!!"
  --> ["1"]
TODO: EOL = "!!!!!!!!", RS = "!"
      "1,2,3!!!!!!!!4,5,6!!!!!!!!"
  --> ["1", "2", "3!"]
TODO: EOL = "!!!!!!!!!!", RS = ""
      "1,2,3!!!!!!!!!!4,5,6!!!!!!!!!!"
  --> ["1"]
TODO: EOL = "!!!!!!!!!!", RS = "!"
      "1,2,3!!!!!!!!!!4,5,6!!!!!!!!!!"
  --> ["1", "2", "3!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = ""
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "\n"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!\n"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!!!!!\n"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "\n!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!"]
TODO: EOL = "\n!!!!!\n!!!!!", RS = "!\n!"
      "1,2,3\n!!!!!\n!!!!!4,5,6\n!!!!!\n!!!!!"
  --> ["1", "2", "3\n!!!!!\n!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = ""
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "\n"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!\n"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "\n!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n!"]
TODO: EOL = "!!!!!\n!!!!!\n", RS = "!\n!"
      "1,2,3!!!!!\n!!!!!\n4,5,6!!!!!\n!!!!!\n"
  --> ["1", "2", "3!!!!!\n!"]
TODO: EOL = "\%^+_\n\0!X**", RS = ""
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1"]
TODO: EOL = "\%^+_\n\0!X**", RS = "\n"
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1", "2", "3\%^+_\n"]
TODO: EOL = "\%^+_\n\0!X**", RS = "!"
      "1,2,3\%^+_\n\0!X**4,5,6\%^+_\n\0!X**"
  --> ["1", "2", "3\%^+_\n\0!"]
TODO: EOL = "\r\n", RS = ""
      "1,2,3\r\n4,5,6\r\n"
  --> ["1"]
TODO: EOL = "\r", RS = ""
      "1,2,3\r4,5,6\r"
  --> ["1"]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'Content'
# at t/90_csv.t line 105
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Str   (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 125
# expected: 'bar,baz,foo
1,2,3
2,a b,
'
#      got: 'foo,bar,baz
# 3,1,2
# 2,a b,
# '
# expected: 'bar,baz,foo
# 1,2,3
# 2,a b,
# '
#      got: 'foo,bar,baz
# 3,1,2
# 2,a b,
# '
# Failed test 'csv => Array (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 134
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Hash  (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 139
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'csv => Hash + skip (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 146
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("3"), :baz("1"), :foo("2")}, {:bar("2"), :baz("a b"), :foo("")}]
# Failed test 'csv => Hash + auto (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 153
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'csv => Block (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 162
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Block (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 169
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 188
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 202
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Channel (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 216
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 226
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 235
# expected: $[["bar", "baz", "foo"], ["1", "2", "3"], ["2", "a b", ""]]
#      got: $[["foo", "bar", "baz"], ["3", "1", "2"], ["2", "a b", ""]]
# Failed test 'csv => Supplier (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 244
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'csv => Hash + hdrs (Array of Hash)  [{bar => 1, baz => 2, foo => 3} {bar => 2, baz => a b, foo => }]'
# at t/90_csv.t line 252
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("3"), :baz("1"), :foo("2")}, {:bar("2"), :baz("a b"), :foo("")}]
# Failed test 'AOH parse out'
# at t/90_csv.t line 268
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Failed test 'AOH parse out no header'
# at t/90_csv.t line 271
# expected: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("2"), :baz("a b"), :foo("")}]
#      got: $[{:bar("1"), :baz("2"), :foo("3")}, {:bar("a b"), :baz(""), :foo("2")}]
# Looks like you failed 20 tests of 428
Aborting due to test failure: Text::CSV:ver<0.008>:auth<github:Tux> (use --force-test to override)
===> Testing [FAIL]: Text::CSV:ver<0.008>:auth<github:Tux>
https://github.com/Tux/CSV

**Comment by Tux** [comment]
On today's rakudo, I get a full pass
```
$ perl6 --version
This is Rakudo version 2019.03-32-g33e2d7f4c built on MoarVM version 2019.03-11-g7ae6684f4
implementing Perl 6.d.

$ make test
:
prove -j4 -e 'perl6 -I. -Ilib' t
t/16_methods.t .... ok
t/10_base.t ....... ok
:
t/99_meta.t ....... ok
All tests successful.
Files=30, Tests=22465, 23 wallclock secs ( 2.55 usr  0.19 sys + 89.43 cusr  2.29 csys = 94.46 CPU)
Result: PASS
```

**Comment by michael-776** [comment]
So is this something I should report to the release-candidate people?

**Comment by lizmat** [comment]
Yes, that seems like a good idea.

**Comment by AlexDaniel** [comment]
Definitely.

**Comment by michael-776** [comment]
OK, filed https://github.com/rakudo/rakudo/issues/2763

**Comment by michael-776** [comment]
Copying this comment from https://github.com/rakudo/rakudo/issues/2763 

I discovered the "zef nuke StoreDir TempDir" command, and after using that I was able to do a successful "zef install Text::CSV"
So maybe just a corrupted download?
I thought I had deleted the old source download before when looking at the problem, I guess I was wrong. Sorry about that.
