### ISSUE TITLE
The Supply tests in t/90_csv.t are broken when run on a post-GLR perl6.

### ISSUE THREAD

**Issue by cschwenz** [Tux/CSV#2]
The symptom of the breakage is when the first `for in () -> $in { ... }` loop gets to the Supply test, `Text::CSV.csv(in => $in, meta => False)` never returns.

Skipping the Supply test and running the remaining tests results in `t/90_csv.t` passing.

**Comment by Tux** [comment]
Thanks for feedback and getting involved!

I think this specific issue is a timing-based thing.
I think that if you play with the sleep value in https://github.com/Tux/CSV/blob/master/t/90_csv.t#L68 you will be able to get t/90_csv.t passing.

If you know a better or more reliable way to have this tested, I am all open to suggestions.

**Comment by cschwenz** [comment]
I've set up a pull request with a proposed work-around for the timing issues.

**Comment by Tux** [comment]
As I do not think the delay has to be recalculated on every call to in, I have extracted your proposal to s sub with a state variable. Tests still pass on my box.

Does this work for you too? (pushed)

**Comment by cschwenz** [comment]
Heh, t/90_csv.t is now passing while t/79_callbacks.t is now the problem child.

    $ panda install Text::CSV
    ==> Fetching Text::CSV
    ==> Building Text::CSV
    ==> Testing Text::CSV
    t/10_base.t ....... ok
    t/12_acc.t ........ ok
    t/15_flags.t ...... ok
    t/16_methods.t .... ok
    t/20_file.t ....... ok
    t/21_combine.t .... ok
    t/22_print.t ...... ok
    t/30_field.t ...... ok
    t/31_row.t ........ ok
    t/32_getline.t .... ok
    t/40_misc.t ....... ok
    t/41_null.t ....... ok
    t/50_utf8.t ....... ok
    t/55_combi.t ...... ok
    t/60_samples.t .... ok
    t/65_allow.t ...... ok
    t/75_hashref.t .... ok
    t/77_getall.t ..... ok
    t/78_fragment.t ... ok
    t/79_callbacks.t .. 
    No subtests run 
    t/80_diag.t ....... ok
    t/81_subclass.t ... ok
    t/82_subclass.t ... ok
    t/90_csv.t ........ ok
    t/91_csv_cb.t ..... ok

    Test Summary Report
    -------------------
    t/79_callbacks.t (Wstat: 139 Tests: 0 Failed: 0)
      Non-zero wait status: 139
      Parse errors: No plan found in TAP output
    Files=25, Tests=19654, 1669 wallclock secs (16.17 usr  0.90 sys + 1614.67 cusr 16.55 csys = 1648.29 CPU)
    Result: FAIL
    test stage failed for Text::CSV: Tests failed
      in method throw at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
      in method install at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
      in method resolve at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:18
      in block <unit> at /home/cschwenz/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda:95


    Failure Summary
    ----------------
    Text::CSV(
      *test stage failed for Text::CSV: Tests failed)

**Comment by Tux** [comment]
```
$ panda install .
==> Installing Text::CSV from a local directory '.'
==> Fetching Text::CSV
==> Building Text::CSV
==> Testing Text::CSV
t/10_base.t ....... ok
t/12_acc.t ........ ok
t/15_flags.t ...... ok
t/16_methods.t .... ok
t/20_file.t ....... ok
t/21_combine.t .... ok
t/22_print.t ...... ok
t/30_field.t ...... ok
t/31_row.t ........ ok
t/32_getline.t .... ok
t/40_misc.t ....... ok
t/41_null.t ....... ok
t/50_utf8.t ....... ok
t/55_combi.t ...... ok
t/60_samples.t .... ok
t/65_allow.t ...... ok
t/75_hashref.t .... ok
t/77_getall.t ..... ok
t/78_fragment.t ... ok
t/79_callbacks.t .. ok
t/80_diag.t ....... ok
t/81_subclass.t ... ok
t/82_subclass.t ... ok
t/90_csv.t ........ ok
t/91_csv_cb.t ..... ok
All tests successful.
Files=25, Tests=19732, 196 wallclock secs ( 1.87 usr  0.10 sys + 188.60 cusr  1.90 csys = 192.47 CPU)
Result: PASS
==> Installing Text::CSV
Copying blib/lib/Text/CSV.pm to /pro/3gl/CPAN/rakudobrew/moar-nom/install/share/perl6/site/lib/Text/CSV.pm
==> Successfully installed Text::CSV
```
Could you try from a git-checkout?
And if it still fails
```
$ perl6 -Ilib t/79_callbacks.t
```

**Comment by cschwenz** [comment]
Hmm, I re-ran `panda install Text::CSV` and this time it installed.  So I'm chalking it up to yet another latent timing issue.  :-/

Anyhow, thank you for your help today!  :-)
