### ISSUE TITLE
License

### ISSUE THREAD

**Issue by coke** [Tux/CSV#27]
Can you please include a specific license in the README and a LICENSE file? The "same terms" line makes it harder to determine the license for corporate users, and the reference to Perl after the Raku rename adds more confusion.

Thanks.

**Comment by JJ** [comment]
Gotcha. I guess Artistic 2.0 is it...

**Comment by Tux** [comment]
What should I change? @JJ  PR welcome :)

**Comment by Tux** [comment]
Ah, I'll change a few words
```
$ grep lic META6.json
  "license"       : "Artistic-2.0",
```
was there already

**Comment by Tux** [comment]
https://github.com/Tux/CSV/commit/fccad062c6b90d62a9b8f5a75dbe2b00c9444cac
