### ISSUE TITLE
Update documentation example? E.g. changing `sep_char` to `sep`, and changing `*STDOUT` to `$*OUT`

### ISSUE THREAD

**Issue by jubilatious1** [Tux/CSV#29]
https://github.com/Tux/CSV/blob/master/doc/Text-CSV.pdf 

The PDF says the following on page 34:

Rewriting CSV
Rewrite CSV files with ; as separator character to well-formed CSV: use Text::CSV qw( csv );
 `csv(in => csv(in => "bad.csv", sep_char => ";"), out => *STDOUT);`

Note: I've had success changing `sep_char` (or `sep-set`) to `sep`, and changing `*STDOUT` to `$*OUT`

`csv(in => csv(in => "bad.csv", sep => ";"), out => $*OUT);`

**Comment by Tux** [comment]
Thank you, fixed in https://github.com/Tux/CSV/commit/1ec5f72e3668fc45718f58545c19acfa1299ef77 which is used to generate the statis codcs in https://github.com/Tux/CSV/commit/579ed85fb54c4eb5ab94d3576a1a8b98afad745a

**Comment by jubilatious1** [comment]
https://unix.stackexchange.com/a/722776/227738

Comments welcome!
