### ISSUE TITLE
Possible author comment on StackOverflow?

### ISSUE THREAD

**Issue by jubilatious1** [Tux/CSV#31]
https://stackoverflow.com/questions/56082707/textcsv-supported-encodings

StackOverflow question from 2019 on Raku's `Text::CSV` file encodings could use a comment from the module's author (especially now that the issue appears resolved).

**Comment by JJ** [comment]
I don't know if I'm one of the authors; I certainly have privs here. And my comment is there. Is there anything I can help with?

**Comment by jubilatious1** [comment]
Maybe it's me who is mis-understanding. If a Repo is under "Raku Community Modules" then I would expect a Community Member's answer to suffice. If a Repo is under "Tux" then some readers might presume the issue still persists until "Tux" chimes in to say it was resolved ( in version X.Y.Z, etc.).

**Comment by lizmat** [comment]
hmmm... I'm not sure Tux does StackOverflow @Tux ??

**Comment by Tux** [comment]
/me does not actively "do" StackOverflow. I /think/ I do have an acoount, but I rarely visit SO, just when people point me there.

Feel free to answer there on behalf of me: you know more about Raku than I do :)
