### ISSUE TITLE
install fails for rakudo 2023.06: "No such method 'depends' for invocant of type 'Any'

### ISSUE THREAD

**Issue by bduggan** [Tux/CSV#33]
Hello,

I'm seeing the following test failure during installation on the latest version of rakudo

```
[META6] #   ($json, @x)
[META6] #   (Any:D $json, Mu $)
[META6] # Failed test 'and they're all META6 objects'
[META6] # at t/040-projects.t line 25
[META6] No such method 'depends' for invocant of type 'Any'
[META6]   in block  at t/040-projects.t line 27
[META6]   in block <unit> at t/040-projects.t line 16
[META6] Type check failed in assignment to $!depends; expected <anon> but got Mu (Mu.new)

$ raku --version
Welcome to Rakudo™ v2023.06.
Implementing the Raku® Programming Language v6.d.
Built on MoarVM version 2023.06.
```
thanks

**Comment by lizmat** [comment]
This feels like another case of https://github.com/rakudo/rakudo/issues/5318

**Comment by JJ** [comment]
What do you think would be the best course of action here? Try a fix or wait for it to be fixed upstream?

**Comment by bduggan** [comment]
I guess this is outside the scope of Text::CSV -- the dependency goes Text::CSV -> Test::META -> META6 -- so looks like the root cause is addressed in https://github.com/jonathanstowe/META6/issues/29 -- I'll go ahead and close this one.
