### ISSUE TITLE
The default/error behavior for the CSV input file is seldom reached

### ISSUE THREAD

**Issue by JJ** [Tux/CSV#39]
While working for #21, I've realized that these lines

https://github.com/Tux/CSV/blob/916c30e37fdd7db7900849e99c823f98444095cf/lib/Text/CSV.rakumod#L1792-L1794

Can only be reached if the input type does not subclass `Any`, which is extremely difficult to happen, because most classes but `Junction`s and `Mu` subclass it. That drops us into (possibly) unintended territory, because the default behavior for `Any` is to wait for standard input (which is what happens in #21, actually)

**Comment by Tux** [comment]
Nice analysis. This indeed is uncharted territory and has no counterpart in Perl5's Text::CSV_XS.
When I made the translation to Perl6 and later to Raku, I tried to implement *all* possible types that could even remotely be a source for CSV data. I am sure I missed some, and I am also sure I chose implementations that I would have done different when done today.
I'll just take your advice
