### ISSUE TITLE
Is MANIFEST still needed?

### ISSUE THREAD

**Issue by JJ** [Tux/CSV#42]
I'm not sure this is still mirrored on CPAN, or if this is used for something
else. If nothing else, it's a list of the files that *actually* constitute the
distribution, so might be a good idea to keep it.

**Comment by Tux** [comment]
MANIFEST is a remnant of the perl distribution. You can change it to whatever best suits the raku ecosystem
This probably also addresses the other question in where people wonder about the files for the other speed tests: these are *not* in MANIFEST
